### ISSUE TITLE
dl link broken

### ISSUE THREAD

**Issue by core-code** [tjluoma/office2011#3]
Fetching X18-08827.dmg

curl: (22) The requested URL returned error: 404 The specified resource does not exist.

**Comment by tjluoma** [comment]
According to http://www.heidoc.net/joomla/technology-science/microsoft/61-office-2011-for-mac-direct-download-links Microsoft has taken all of the download links off-line.

Not sure what to do about this for the moment.

**Comment by core-code** [comment]
here are official links:

http://officecdn.microsoft.com/pr/MacOffice2011/de-DE/MicrosoftOffice2011.dmg

replace de-DE with other languages as necessary
